// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2z-ZdBXSxnjbgSmdzOZZWp4kzQRXdSsU',
    appId: '1:823877432364:web:b2f585a925d5b9c41ecd89',
    messagingSenderId: '823877432364',
    projectId: 'chat-app-49a98',
    authDomain: 'chat-app-49a98.firebaseapp.com',
    storageBucket: 'chat-app-49a98.appspot.com',
    measurementId: 'G-76LX72MNJ3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwIpT9LKzvHGWoFtlsAPU3iKDBpH8Gm-Q',
    appId: '1:823877432364:android:871ba3a7eb68df741ecd89',
    messagingSenderId: '823877432364',
    projectId: 'chat-app-49a98',
    storageBucket: 'chat-app-49a98.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqvc5F9KjjHFt7KCqx2YV216rGviYfKpg',
    appId: '1:823877432364:ios:cfd92680b1cc5e271ecd89',
    messagingSenderId: '823877432364',
    projectId: 'chat-app-49a98',
    storageBucket: 'chat-app-49a98.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqvc5F9KjjHFt7KCqx2YV216rGviYfKpg',
    appId: '1:823877432364:ios:cfd92680b1cc5e271ecd89',
    messagingSenderId: '823877432364',
    projectId: 'chat-app-49a98',
    storageBucket: 'chat-app-49a98.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2z-ZdBXSxnjbgSmdzOZZWp4kzQRXdSsU',
    appId: '1:823877432364:web:0e8a925d295692c61ecd89',
    messagingSenderId: '823877432364',
    projectId: 'chat-app-49a98',
    authDomain: 'chat-app-49a98.firebaseapp.com',
    storageBucket: 'chat-app-49a98.appspot.com',
    measurementId: 'G-VGY5DTS0KR',
  );
}
